### ISSUE TITLE
UI: show submission events

### ISSUE THREAD

**Issue by privat** [Morriar/Missions#100]
In #99, specific events are attached to specific submissions, the UI should show them
- mission solved (for the first time)
- star unlocked (for the first time)
- new high-score (each time a better high-score is obtained for a star)

**Comment by privat** [comment]
This is great. however i'm not fan of the progress bar, especially since the goal is lower than the score.
moreover, if I beat the goal (eg score=15 goal=17), then the progressbar is shown incomplete :/

**Comment by Morriar** [comment]
Do you have a better idea that does not look like a debian manpage?
