### ISSUE TITLE
Add Full Name and Display Name to player model

### ISSUE THREAD

**Issue by ppepos** [Morriar/Missions#20]
Currently, only the github account name is ever displayed. It would be simpler to include the Full Name and allow players to set themselves a custom Display Name (even if linked with the github account). This would make finding friends and managing a class or group easier I believe.

**Comment by Morriar** [comment]
One thing though, an integration with shibolleth is undergoing by @privat. The idea is to use the student names directly from the university database.

**Comment by ppepos** [comment]
Seems 100% legit. Closing!
