### ISSUE TITLE
Mission overlay (on hover) is rebelling

### ISSUE THREAD

**Issue by ppepos** [Morriar/Missions#22]
The overlay for mmissions seems to still be suffering from the filthy rebellious theming. Should we correct these fault overlays and bring them to the light side of society? (aka pale theme. dark theme is evil, hackers use dark themes. white themes are pure and corporate compliant)

May the light be with you.

**Comment by Morriar** [comment]
Actually, I was considering turning all the style more darkish or colorish?

**Comment by privat** [comment]
closed by #97
