### ISSUE TITLE
Mission of the week

### ISSUE THREAD

**Issue by privat** [Morriar/Missions#3]
Each week a new mission, and achievement for dedication on solving weekly mission..

**Comment by Morriar** [comment]
The notification system will be used to alert for new missions / missions of the week.

**Comment by Morriar** [comment]
The achievement system will be used to reward players.

**Comment by Morriar** [comment]
@privat we need the to talk about the mission system.

Also, when do we reward the `all mission` achievement? Each week and the achievement is lost when a new challenge appears?

**Comment by privat** [comment]
missions of the week should be considered an extra/bonus level.
Do not worry about this feature now.

**Comment by Morriar** [comment]
I still have some questions...

Is the mission of the week chosen by the "admin" or is it like the last mission added?

**Comment by privat** [comment]
I have no idea. It was just a random proposal. In fact I m not sure it
worth it to disable some missions after some time.

Le lun. 19 sept. 2016 17:41, Alexandre Terrasa notifications@github.com a
écrit :

**Comment by Morriar** [comment]
Hum I only saw that as a way to highlight/promote specific missions, didn't though of the `locking` aspect.

**Comment by privat** [comment]
I just close the issue. The more I think, the less it seems to make sense.
