### ISSUE TITLE
Misleading label

### ISSUE THREAD

**Issue by privat** [Morriar/Missions#41]
When you click on the top-left `Missions` you get the podium and the list of users, not the list of missions.

**Comment by Morriar** [comment]
Because Missions is the name of the site hence, the main menu.

We can improve that, what are you proposing?

**Comment by privat** [comment]
- [ ] rename the project?
- [ ] add real menu entry in a navbar?
- [x] make 'missions' looks like a logo, not a menu entry?

**Comment by Morriar** [comment]
Opted in option #3, find a logo or something.

At this point this can be only a glyphicon? 

http://getbootstrap.com/components/

**Comment by privat** [comment]
glyphicon-road: partons [à l'aventure](https://www.youtube.com/watch?v=LclYvbuHc9s)?
glyphicon-sunglasses: [traite avec ça](http://knowyourmeme.com/memes/deal-with-it)?
glyphicon-flag: CTF?

**Comment by Morriar** [comment]
Icon flag is not a so bad idea since we have it on eveypage?
