### ISSUE TITLE
Displayed login methods should reflect the real available auth

### ISSUE THREAD

**Issue by privat** [Morriar/Missions#44]
Since #36, github and uqam login auth are shown in the UI, unfortunately, the real valid login-routes depends on with `src/api/api_auth_*` module is loaded (mixed-in).
Moreover, by default (`make`) only the github auth is used.

TODO: The displayed login methods should reflect the real available auth.

**Comment by Morriar** [comment]
Can both Github and Shib be used together with the mixim way?

**Comment by privat** [comment]
I do not know.
For short term, I think that one or the other will be activated separately.
