### ISSUE TITLE
UI: improve navigation

### ISSUE THREAD

**Issue by privat** [Morriar/Missions#70]
on a mission page:
- return to the track

on a track page:
- return to the list of tracks

**Comment by ppepos** [comment]
The navbar needs to be completed at least. Do you feel like [breadcrumbs](http://v4-alpha.getbootstrap.com/components/breadcrumb/#content) could also be intuitive?

**Comment by privat** [comment]
breadcrumbs are easy to understand, usual and adapted to our model.

something like

```
Tracks > $currenttrack > $currentmission
```

could be nice, indeed.

**Comment by ppepos** [comment]
Deal. Breadcrumbs will be added.
