### ISSUE TITLE
open/solved icon

### ISSUE THREAD

**Issue by privat** [Morriar/Missions#73]
using glyphicon-remove (X) for open missions is quite unintuitive.
Maybe use glyphicon-play (▶) or glyphicon-play-circle (the same in a circle)

By the way, using a flag (⚑) for success might better that a checkmark (✓), as the flag seems used elsewhere to mean _solved missions_.

**Comment by ppepos** [comment]
+1
+1

**Comment by privat** [comment]
closed by #97
